// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  int32                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	Dest  int32                  `protobuf:"varint,2,opt,name=Dest,proto3" json:"Dest,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_Paint
	//	*Packet_Chat
	//	*Packet_Game
	//	*Packet_NewGame
	Payload       isPacket_Payload       `protobuf_oneof:"Payload"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Packet) GetDest() int32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetPaint() *PaintMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Paint); ok {
			return x.Paint
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetGame() *GameMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Game); ok {
			return x.Game
		}
	}
	return nil
}

func (x *Packet) GetNewGame() *NewGameMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_NewGame); ok {
			return x.NewGame
		}
	}
	return nil
}

func (x *Packet) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_Paint struct {
	Paint *PaintMessage `protobuf:"bytes,3,opt,name=paint,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,4,opt,name=chat,proto3,oneof"`
}

type Packet_Game struct {
	Game *GameMessage `protobuf:"bytes,5,opt,name=game,proto3,oneof"`
}

type Packet_NewGame struct {
	NewGame *NewGameMessage `protobuf:"bytes,6,opt,name=newGame,proto3,oneof"`
}

func (*Packet_Paint) isPacket_Payload() {}

func (*Packet_Chat) isPacket_Payload() {}

func (*Packet_Game) isPacket_Payload() {}

func (*Packet_NewGame) isPacket_Payload() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaintMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectedUsers []*User                `protobuf:"bytes,1,rep,name=ConnectedUsers,proto3" json:"ConnectedUsers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaintMessage) Reset() {
	*x = PaintMessage{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaintMessage) ProtoMessage() {}

func (x *PaintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaintMessage.ProtoReflect.Descriptor instead.
func (*PaintMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *PaintMessage) GetConnectedUsers() []*User {
	if x != nil {
		return x.ConnectedUsers
	}
	return nil
}

type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SSID          string                 `protobuf:"bytes,1,opt,name=SSID,proto3" json:"SSID,omitempty"`
	Play          string                 `protobuf:"bytes,2,opt,name=Play,proto3" json:"Play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *GameMessage) GetSSID() string {
	if x != nil {
		return x.SSID
	}
	return ""
}

func (x *GameMessage) GetPlay() string {
	if x != nil {
		return x.Play
	}
	return ""
}

type NewGameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	Dest          int32                  `protobuf:"varint,2,opt,name=Dest,proto3" json:"Dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameMessage) Reset() {
	*x = NewGameMessage{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameMessage) ProtoMessage() {}

func (x *NewGameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameMessage.ProtoReflect.Descriptor instead.
func (*NewGameMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *NewGameMessage) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *NewGameMessage) GetDest() int32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\x06Packet\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x05R\x04From\x12\x12\n" +
	"\x04Dest\x18\x02 \x01(\x05R\x04Dest\x12.\n" +
	"\x05paint\x18\x03 \x01(\v2\x16.protocol.PaintMessageH\x00R\x05paint\x12+\n" +
	"\x04chat\x18\x04 \x01(\v2\x15.protocol.ChatMessageH\x00R\x04chat\x12+\n" +
	"\x04game\x18\x05 \x01(\v2\x15.protocol.GameMessageH\x00R\x04game\x124\n" +
	"\anewGame\x18\x06 \x01(\v2\x18.protocol.NewGameMessageH\x00R\anewGame\x12=\n" +
	"\flast_updated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedB\t\n" +
	"\aPayload\"'\n" +
	"\vChatMessage\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContent\"2\n" +
	"\x04User\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\x05R\x02Id\"F\n" +
	"\fPaintMessage\x126\n" +
	"\x0eConnectedUsers\x18\x01 \x03(\v2\x0e.protocol.UserR\x0eConnectedUsers\"5\n" +
	"\vGameMessage\x12\x12\n" +
	"\x04SSID\x18\x01 \x01(\tR\x04SSID\x12\x12\n" +
	"\x04Play\x18\x02 \x01(\tR\x04Play\"8\n" +
	"\x0eNewGameMessage\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x05R\x04From\x12\x12\n" +
	"\x04Dest\x18\x02 \x01(\x05R\x04DestB\"Z github.com/persona-mp3/protocolsb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*Packet)(nil),                // 0: protocol.Packet
	(*ChatMessage)(nil),           // 1: protocol.ChatMessage
	(*User)(nil),                  // 2: protocol.User
	(*PaintMessage)(nil),          // 3: protocol.PaintMessage
	(*GameMessage)(nil),           // 4: protocol.GameMessage
	(*NewGameMessage)(nil),        // 5: protocol.NewGameMessage
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	3, // 0: protocol.Packet.paint:type_name -> protocol.PaintMessage
	1, // 1: protocol.Packet.chat:type_name -> protocol.ChatMessage
	4, // 2: protocol.Packet.game:type_name -> protocol.GameMessage
	5, // 3: protocol.Packet.newGame:type_name -> protocol.NewGameMessage
	6, // 4: protocol.Packet.last_updated:type_name -> google.protobuf.Timestamp
	2, // 5: protocol.PaintMessage.ConnectedUsers:type_name -> protocol.User
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Paint)(nil),
		(*Packet_Chat)(nil),
		(*Packet_Game)(nil),
		(*Packet_NewGame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
